Mini Reddit
SevlaMare/reddit pull request #1
Opened 2020-04-28 15:09 UTC by SevlaMare

-Setup
-

2020-05-12 01:01 UTC, majovanilla requested changes
Hey team!!

## Great job on this project! 👍

You made almost everything perfect!! Just a few things before moving to the next project.
- Please keep in mind that the model names matter on this side of the review. In this case, you changed the `user` model to `author` model and that's ok, but it would make our TSE's lives easier if you follow the instructions and name conventions on the Odin Project on the following projects!! :pray: 


There are still some changes 👇 you need to implement to approve this request 🔍 Please check the comments below and make the **required** changes.

If you want to make your project even better 🔥💥, I left a few suggestions you can implement.  Those are marked as **optional**.


If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

2020-05-12 15:23 UTC, SevlaMare commented on app/models/post.rb
> +  validates :title, presence: true, uniqueness: true
We are thinking about having article with same title, can be bad when you try to search a specific article, but like you say, out there they allow duplicate titles.

2020-05-13 02:05 UTC, SevlaMare commented on app/models/comment.rb
> +  belongs_to :post
We solve the required, but we are unable to solve the direct access to the object, like
`Post.first.comments.create(body: "some text")`

2020-05-13 02:10 UTC, SevlaMare commented on app/models/comment.rb
> +  belongs_to :post
We solve the required, but we are unable to solve, for now, the direct access to the object, like
`Post.first.comments.create(body: "some text")`

2020-05-13 02:12 UTC, SevlaMare commented on app/models/comment.rb
> +  belongs_to :post
We solve the required, but we are unable to set direct access to the object, like
`Post.first.comments.create(body: "some text")`

2020-05-13 02:12 UTC, SevlaMare commented on app/models/comment.rb
> +  belongs_to :post
We solve the required, but for now, we are unable to set direct access to the object, like
`Post.first.comments.create(body: "some text")`

2020-05-13 14:45 UTC, jofer86 approved these changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- The required changes were met, this project is now complete!! 

# `status: approved` :rocket: :rocket: :+1: :+1: 
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-05-13 16:35 UTC, merged